### PR TITLE
Fix JSON numbers being incorrectly set as integers.

### PR DESCRIPTION
**Pull request by dpc**
Issue #108

### CODE REVIEW

**Comment by dpc** [comment]
OK. So here I am confused. There are two contradicting tests.

* `test_ser_datetime`
* `oid`

The decision has to be made. Either (de-)serializating  is to Rust native types (`test_ser_date`) or to types where stuff was decomposed to types used in the "Strict Mode Json". I don't think it's possible to have both, without ambiguities. But I'm tired, and I might be confused.

It seems to me, it should be Rust native types, in which case `oid` test is wrong. If the user wants to get the `ObjectId`, they should have used that type, and not a map `{'$oid': "string"}`.

The way I see it, `Bson` can be converted back and forth between Rust types. The "Strict Mode JSON" is just a way to convert BSon to a JSON-compatible encoding, and back. They are separate concepts, for different applications. So the String-Mode encoding functions should never be called from within anything that has to do with `Bson <-> Rust Types` conversions.

**Comment by dpc** [comment]
Oh... strike of enlightenment... So the whole thing is because `serde` has no way to express serialization and deserialization of types that are not native to Rust?

**Comment by dpc** [comment]
It seems I digged myself out of a hole. The Travis-CI fail is nightly only.

I've ported my changed to 0.11.3 (for mongo_driver) and now the imported data is.. `0.0` instead of `0`. So I guess technically correct, but not what I expected. I thought that `0.0` is `0`...

**Comment by dpc** [comment]
I should probably move the two other changes to a separate PR, but I'll wait to see what you think...

**Comment by patrickfreed** [comment]
This works as designed. See my comment on #108. Thank you for submitting the pull request though!

**Comment by patrickfreed** [comment]
I will add that the following is definitely true and is something we plan to improve in the future:
>The way I see it, Bson can be converted back and forth between Rust types. The "Strict Mode JSON" is just a way to encode BSon in a JSON, and back. These are separate concepts, for different use cases. So the Strict-Mode encoding functions should never be called from within anything that has to do with Bson <-> Rust Types conversions. It seems to me they are conflated now, so I can't complete this fix.

See RUST-426 for the ticket to track the work for investigating this.

**Pull request closed without merging**
