### PR TITLE
RUST-686 Update base64 dependency

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-686

**Comment by isabelatkinson** [comment]
Hi @bugadani, thanks for the pull request! I'm seeing a few clippy failures in our CI that have been fixed in a recent commit -- would you mind rebasing on master to get these changes? You can run `bash .evergreen/check-clippy.sh` once you've rebased to verify that there are no more errors.

**Comment by bugadani** [comment]
@isabelatkinson I've rebased onto master but I still see numerous errors. To be honest, I don't think those errors belong to the scope of this PR, though.

**Review by isabelatkinson — APPROVED** [review]
The rebase cleaned up the clippy failures on our end. This looks good to me, tagging in the rest of the team for review!

**Review by saghm — APPROVED** [review]

**Review by patrickfreed — APPROVED** [review]

**Comment by isabelatkinson** [comment]
@bugadani Thanks for your contribution!

**Pull request merged**
