### PR TITLE
RUST-2017 Add method to construct an `ObjectId` from its parts

### PR DESCRIPTION
**Pull request by tyilo**

### CODE REVIEW

**Comment by abr-egn** [comment]
Can I ask about the use case for this?  Synthesizing ObjectIds seems likely to run into unexpected collisions or other subtle issues.

**Comment by tyilo** [comment]
> Can I ask about the use case for this?
The use case is that I want to find documents in a specific time interval. The collection doesn't have any indexes, however the auto-created `_id` can be used for this.

> Synthesizing ObjectIds seems likely to run into unexpected collisions or other subtle issues.\
This is already possible using `ObjectId::from_bytes`

**Review by abr-egn — APPROVED** [review]
LGTM!

**Review by isabelatkinson — COMMENTED** [review]
changes look good, can we add a simple test for this in `src/tests/modules/oid.rs`?

**Comment by tyilo** [comment]
> changes look good, can we add a simple test for this in `src/tests/modules/oid.rs`?

Done

**Review by isabelatkinson — APPROVED** [review]
lgtm, thanks for your contribution!

**Pull request merged**
